site_name: [Site Name]
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
  language: en

# docs to modify the palette https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

  palette:
    - scheme: mod
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: light blue

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - callouts

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

